package project

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/heydon/dconsole/internal/alias"
)

// Detection holds what dconsole could discover at a candidate project
// root. Empty Sources means there's nothing to generate from.
type Detection struct {
	Root         string
	ProjectName  string
	Sources      []string         // human-readable list of detected sources
	Defaults     alias.Alias      // suggested _defaults block
	Envs         map[string]alias.Alias
	DefaultEnv   string
}

// Detect walks `start` looking for indicators of a Drupal-shaped project
// and returns what it found. Returns (nil, nil) if nothing actionable
// turned up — callers should treat that as "can't generate."
//
// Currently understands:
//   - composer.json with drupal/core* in require → confirms it's Drupal
//     and gives a project name.
//   - .ddev/config.yaml → adds a `local` env via ddev transport.
//   - drush/sites/*.site.yml (or self.site.yml) → converts those envs.
//
// It deliberately walks UP from `start` looking for these (composer.json
// might be a few dirs above the cwd in a monorepo).
func Detect(start string) (*Detection, error) {
	root := findProjectRoot(start)
	if root == "" {
		return nil, nil
	}
	d := &Detection{Root: root, Envs: map[string]alias.Alias{}}
	d.ProjectName = filepath.Base(root)

	if name, ok := composerProjectName(root); ok {
		d.Sources = append(d.Sources, "composer.json (drupal project)")
		d.ProjectName = name
	}

	if name, ok := ddevProjectName(root); ok {
		d.Sources = append(d.Sources, ".ddev/config.yaml (name="+name+")")
		if d.ProjectName == filepath.Base(root) {
			d.ProjectName = name
		}
		d.Envs["local"] = alias.Alias{
			URI:       "https://" + name + ".ddev.site",
			Bin:       alias.RemoteBin{Kind: "auto"},
			Transport: alias.Transport{Type: "ddev", DDEV: &alias.DDEVTransport{Project: name}},
		}
		d.DefaultEnv = "local"
	}

	if envs, src, err := drushAliases(root); err != nil {
		return nil, err
	} else if envs != nil {
		d.Sources = append(d.Sources, src)
		for k, v := range envs {
			if _, exists := d.Envs[k]; !exists {
				d.Envs[k] = v
			}
		}
		if d.DefaultEnv == "" {
			d.DefaultEnv = pickPreferredEnv(d.Envs)
		}
	}

	if d.ProjectName != "" && len(d.Envs) > 0 {
		// Fill out _defaults heuristically: web root for most Drupal
		// installs is "web/" relative to project root.
		webDir := filepath.Join(root, "web")
		if _, err := os.Stat(webDir); err == nil {
			d.Defaults.Root = webDir
		}
		d.Defaults.Bin.Kind = "auto"
	}

	if len(d.Sources) == 0 || len(d.Envs) == 0 {
		return nil, nil
	}
	return d, nil
}

// Generate writes the detected manifest as YAML to `path`. If `path`
// already exists, returns an error unless `overwrite` is true.
func Generate(d *Detection, path string, overwrite bool) error {
	if !overwrite {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists (pass --force to overwrite)", path)
		}
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return Write(d, f)
}

// Write renders the detected manifest YAML to an arbitrary writer. Used
// for --dry-run and for tests.
func Write(d *Detection, w io.Writer) error {
	root := yaml.Node{Kind: yaml.MappingNode}
	addScalar(&root, "project", d.ProjectName)
	if d.DefaultEnv != "" {
		addScalar(&root, "default_env", d.DefaultEnv)
	}
	if !isZeroAlias(d.Defaults) {
		def, err := nodeFor(d.Defaults)
		if err != nil {
			return err
		}
		addNode(&root, "_defaults", def)
	}
	for _, name := range sortedKeys(d.Envs) {
		env := d.Envs[name]
		node, err := nodeFor(env)
		if err != nil {
			return err
		}
		addNode(&root, name, node)
	}
	fmt.Fprintln(w, "# Generated by `dconsole project:init`. Review and edit as needed.")
	fmt.Fprintln(w, "# Detected sources:")
	for _, s := range d.Sources {
		fmt.Fprintf(w, "#   - %s\n", s)
	}
	fmt.Fprintln(w)
	enc := yaml.NewEncoder(w)
	enc.SetIndent(2)
	defer enc.Close()
	return enc.Encode(&root)
}

// PrintDetection writes a human-readable summary of what Detect found.
func PrintDetection(d *Detection, w io.Writer) {
	if d == nil {
		fmt.Fprintln(w, "(nothing detected)")
		return
	}
	fmt.Fprintf(w, "project root: %s\n", d.Root)
	fmt.Fprintf(w, "project name: %s\n", d.ProjectName)
	if d.DefaultEnv != "" {
		fmt.Fprintf(w, "default_env:  %s\n", d.DefaultEnv)
	}
	fmt.Fprintln(w, "detected:")
	for _, s := range d.Sources {
		fmt.Fprintf(w, "  - %s\n", s)
	}
	fmt.Fprintln(w, "envs:")
	for _, n := range sortedKeys(d.Envs) {
		e := d.Envs[n]
		fmt.Fprintf(w, "  - %s (transport: %s)\n", n, e.Transport.Type)
	}
}

// --- helpers ---

func findProjectRoot(start string) string {
	abs, err := filepath.Abs(start)
	if err != nil {
		return ""
	}
	dir := abs
	for {
		if hasAnyIndicator(dir) {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func hasAnyIndicator(dir string) bool {
	for _, p := range []string{
		"composer.json",
		".ddev/config.yaml",
		"drush/sites",
	} {
		if _, err := os.Stat(filepath.Join(dir, p)); err == nil {
			return true
		}
	}
	return false
}

type composerJSON struct {
	Name    string                 `json:"name"`
	Require map[string]json.RawMessage `json:"require"`
}

func composerProjectName(root string) (string, bool) {
	data, err := os.ReadFile(filepath.Join(root, "composer.json"))
	if err != nil {
		return "", false
	}
	var c composerJSON
	if err := json.Unmarshal(data, &c); err != nil {
		return "", false
	}
	hasDrupal := false
	for k := range c.Require {
		if strings.HasPrefix(k, "drupal/core") {
			hasDrupal = true
			break
		}
	}
	if !hasDrupal {
		return "", false
	}
	if c.Name == "" {
		return "", false
	}
	// composer name is "vendor/package"; use the package half.
	if i := strings.LastIndex(c.Name, "/"); i >= 0 {
		return c.Name[i+1:], true
	}
	return c.Name, true
}

type ddevConfig struct {
	Name string `yaml:"name"`
}

func ddevProjectName(root string) (string, bool) {
	data, err := os.ReadFile(filepath.Join(root, ".ddev", "config.yaml"))
	if err != nil {
		return "", false
	}
	var c ddevConfig
	if err := yaml.Unmarshal(data, &c); err != nil {
		return "", false
	}
	if c.Name == "" {
		return "", false
	}
	return c.Name, true
}

// drushAliases looks for drush/sites/*.site.yml. Prefers self.site.yml
// if present, otherwise picks the first file alphabetically. Returns
// (envs, source description, err). Envs nil means none found.
func drushAliases(root string) (map[string]alias.Alias, string, error) {
	dir := filepath.Join(root, "drush", "sites")
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, "", nil
		}
		return nil, "", err
	}
	var picked string
	for _, e := range entries {
		if e.Name() == "self.site.yml" {
			picked = e.Name()
			break
		}
	}
	if picked == "" {
		for _, e := range entries {
			if strings.HasSuffix(e.Name(), ".site.yml") {
				picked = e.Name()
				break
			}
		}
	}
	if picked == "" {
		return nil, "", nil
	}
	path := filepath.Join(dir, picked)
	// Reuse the alias converter: it writes rdrush-format yaml; we parse
	// it back to extract the env map.
	var buf strings.Builder
	if _, err := alias.ConvertDrushFile(path, &buf); err != nil {
		return nil, "", fmt.Errorf("convert %s: %w", path, err)
	}
	var envs map[string]alias.Alias
	if err := yaml.Unmarshal([]byte(buf.String()), &envs); err != nil {
		return nil, "", err
	}
	if len(envs) == 0 {
		return nil, "", nil
	}
	return envs, fmt.Sprintf("drush/sites/%s (envs: %s)", picked, strings.Join(sortedKeys(envs), ", ")), nil
}

// pickPreferredEnv returns "dev" if present, then "local", "self",
// otherwise the alphabetically first env.
func pickPreferredEnv(envs map[string]alias.Alias) string {
	for _, pref := range []string{"dev", "local", "self"} {
		if _, ok := envs[pref]; ok {
			return pref
		}
	}
	keys := sortedKeys(envs)
	if len(keys) > 0 {
		return keys[0]
	}
	return ""
}

func sortedKeys(m map[string]alias.Alias) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	alias.SortByLifecycle(keys)
	return keys
}

func nodeFor(v any) (*yaml.Node, error) {
	var n yaml.Node
	if err := n.Encode(v); err != nil {
		return nil, err
	}
	return &n, nil
}

func addScalar(parent *yaml.Node, key, val string) {
	k := &yaml.Node{Kind: yaml.ScalarNode, Value: key}
	v := &yaml.Node{Kind: yaml.ScalarNode, Value: val}
	parent.Content = append(parent.Content, k, v)
}

func addNode(parent *yaml.Node, key string, val *yaml.Node) {
	k := &yaml.Node{Kind: yaml.ScalarNode, Value: key}
	parent.Content = append(parent.Content, k, val)
}

func isZeroAlias(a alias.Alias) bool {
	return a.URI == "" && a.Root == "" && a.Bin.Kind == "" && a.Bin.Path == "" &&
		a.Transport.Type == "" && a.Provider.Type == ""
}
